export const NAV_LABELS = {
	home: "Inicio",
	dashboard: "Dashboard",
	clients: "Clientes",
	treatments: "Tratamientos",
	bonos: "Bonos",
	consents: "Consentimientos",
	budgets: "Presupuestos",
	documents: "Documentos",
	inventory: "Stock",
	calendar: "Agenda",
	finance: "Finanzas",
	invoices: "Facturas",
	suppliers: "Proveedores",
	taxes: "Fiscalidad",
	settings: "Ajustes",

	finance_movements: "Movimientos",
	financial_analysis: "Análisis Financiero",
	assets: "Bienes de Inversión",
};

export const PATH_MAP = {
	home: "/",
	dashboard: "/dashboard",
	clients: "/clientes",
	treatments: "/tratamientos",
	bonos: "/bonos",
	consents: "/consentimientos",
	inventory: "/inventario",
	calendar: "/agenda",
	finance_movements: "/finanzas/movimientos",
	invoices: "/finanzas/facturas",
	financial_analysis: "/finanzas/analisis",
	suppliers: "/proveedores",
	taxes: "/fiscalidad",
	assets: "/fiscalidad/bienes-inversion",
	settings: "/configuracion",
	budgets: "/presupuestos"
};
